name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8, 11]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem

        # Deploy to EC2
        ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          # Update package lists and install Java and Tomcat
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget
          
          # Install Tomcat
          wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.78/bin/apache-tomcat-9.0.78.tar.gz
          tar xzf apache-tomcat-9.0.78.tar.gz
          sudo mv apache-tomcat-9.0.78 /opt/tomcat
          sudo chown -R $EC2_USER:$EC2_USER /opt/tomcat

          # Create a directory for deployment
          mkdir -p /opt/tomcat/webapps

          # Transfer the WAR file to Tomcat's webapps directory
          scp -i private_key.pem -o StrictHostKeyChecking=no ./target/car-booking.webapp.war $EC2_USER@$EC2_HOST:/opt/tomcat/webapps/

          # Start Tomcat (or restart if already running)
          /opt/tomcat/bin/startup.sh
        EOF

    - name: Clean up SSH key
      run: rm -f private_key.pem
